In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [39]:
credits = pd.read_csv("tmdb_5000_credits.csv")

In [49]:
movie = pd.read_csv("tmdb_5000_movies.csv")

In [50]:
movie.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [51]:
movie.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [42]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [52]:
df = movie.merge(
    credits,
    left_on="id",
    right_on="movie_id",
    suffixes=("movie", "_credits")
)

In [53]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'titlemovie', 'vote_average',
       'vote_count', 'movie_id', 'title_credits', 'cast', 'crew'],
      dtype='object')

In [54]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,titlemovie,vote_average,vote_count,movie_id,title_credits,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [58]:
df.rename(columns={"original_title":  "title"}, inplace = True)

In [60]:
df.head()

,movie_id,keywords,overview,title,overview,genres,cast,crew
0,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [63]:
df.columns

Index(['movie_id', 'keywords', 'overview', 'title', 'overview', 'genres',
       'cast', 'crew'],
      dtype='object')

In [64]:
df = df.loc[:, ~df.columns.duplicated()]

In [65]:
df.columns

Index(['movie_id', 'keywords', 'overview', 'title', 'genres', 'cast', 'crew'], dtype='object')

In [74]:
df["tags"] = (
    df["overview"].fillna("") + " " +
    df["genres"].fillna("") + " " +
    df["keywords"].fillna("") + " " +
    df["cast"].fillna("") + " " +
    df["crew"].fillna("")
)

/tmp/ipykernel_1913/3463155045.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["tags"] = (

In [67]:
df.columns

Index(['movie_id', 'keywords', 'overview', 'title', 'genres', 'cast', 'crew',
       'tags'],
      dtype='object')

In [70]:
df= df[
    ["movie_id",
    "keywords",
    "overview",
    "title",
    "overview",
    "genres",
    "cast",
    "crew"
    ]
    ].copy()

In [71]:
df.columns

Index(['movie_id', 'keywords', 'overview', 'overview', 'overview', 'overview',
       'title', 'overview', 'overview', 'overview', 'overview', 'genres',
       'cast', 'crew'],
      dtype='object')

In [72]:
df = df.loc[:, ~df.columns.duplicated()]

In [75]:
df.columns

Index(['movie_id', 'keywords', 'overview', 'title', 'genres', 'cast', 'crew',
       'tags'],
      dtype='object')

In [85]:
from ast import literal_eval

def convert(obj):
    L = []
    for i in literal_eval(obj):
        L.append(i["name"])
    return L

df["genres"] = df["genres"].apply(convert)
df["keywords"] = df["keywords"].apply(convert)

ValueError: malformed node or string: ['Action']

In [86]:
print(df["genres"].iloc[0])
print(type(df["genres"].iloc[0]))

['Action']
<class 'list'>

In [87]:
df["tags"]

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: tags, Length: 4803, dtype: object

In [90]:
df[["title", "tags"]].head()

,title,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca..."

In [96]:
# Coverting tags in vector

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer( max_features = 5000,
                      stop_words = "english")

counter = cv.fit_transform(df["tags"])

print(counter)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 768461 stored elements and shape (4803, 5000)>
  Coords	Values
  (0, 1272)	1
  (0, 3200)	3
  (0, 3408)	1
  (0, 3378)	1
  (0, 4614)	1
  (0, 2077)	1
  (0, 729)	3
  (0, 2561)	261
  (0, 352)	2
  (0, 654)	1
  (0, 88)	3
  (0, 676)	1
  (0, 151)	3
  (0, 1986)	1
  (0, 588)	1
  (0, 4153)	1
  (0, 2025)	1
  (0, 1550)	1
  (0, 365)	1
  (0, 2148)	1
  (0, 4337)	4
  (0, 4841)	2
  (0, 4314)	1
  (0, 408)	1
  (0, 4640)	1
  :	:
  (4802, 2689)	1
  (4802, 2237)	1
  (4802, 317)	1
  (4802, 4114)	1
  (4802, 4970)	1
  (4802, 3568)	1
  (4802, 1540)	2
  (4802, 3701)	1
  (4802, 2964)	1
  (4802, 4667)	1
  (4802, 1779)	3
  (4802, 1473)	1
  (4802, 4302)	1
  (4802, 183)	1
  (4802, 3559)	1
  (4802, 2341)	1
  (4802, 2007)	1
  (4802, 1775)	2
  (4802, 1801)	1
  (4802, 3807)	1
  (4802, 1607)	1
  (4802, 1736)	1
  (4802, 544)	1
  (4802, 918)	3
  (4802, 843)	1

In [97]:
counter.shape

(4803, 5000)

In [101]:
# Step 3 — Calculate similarity

from sklearn.metrics.pairwise import cosine_similarity

cosine = cosine_similarity(counter)

In [103]:
cosine.shape

(4803, 4803)

In [116]:
# recommend system Function 

def recommend(movie):
    index = df[df["title"] == movie].index[0]

    distances = cosine[index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in movies_list:
        print(df.iloc[i[0]]["title"])

In [117]:
recommend("Avatar")

Jupiter Ascending
The Martian
The Amazing Spider-Man
Spectre
2012

In [139]:
# recommend system Function if movie not match
def recommend(movie):
    matches = df[df["title"].str.lower() == movie.lower()]

    if matches.empty:
        print("Movie not found.")
        print("Please check the movie title.")
        return

    index = matches.index[0]

    distances = cosine[index]

    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in movie_list:
        print(df.iloc[i[0]]["title"])

In [138]:
recommend("Avatar")

Jupiter Ascending
The Martian
The Amazing Spider-Man
Spectre
2012

In [140]:
recommend("Avtar")

Movie not found.
Please check the movie title.

In [144]:
# recommend system Function with if movie not match and with suggestion 

from difflib import get_close_matches


def recommend(movie):
    matches = df[df["title"].str.lower() == movie.lower()]

    if matches.empty:
        suggestions = get_close_matches(
            movie,
            df["title"].tolist(),
            n=5,
            cutoff=0.5
        )

        print("Movie not found.")
        print("Did you mean:", suggestions)
        return

    index = matches.index[0]
    distances = cosine[index]

    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    print(f"\nMovies similar to {matches.iloc[0]['title']}:\n")

    for i, score in movie_list:
        print(f"{df.iloc[i]['title']}  → similarity: {score:.3f}")

In [145]:
recommend("Avtar")

Movie not found.
Did you mean: ['Avatar', 'Evita', 'After', 'Ishtar', 'Ararat']

In [147]:
# Next step Improve recommend system 

# Nomalizing text 

def clea_text(text):
    return str(text).lower().replace("","")

In [161]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 1. Create vectorizer
tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

# 2. Convert tags into numerical vectors
vectors = tfidf.fit_transform(df["tags"])

# 3. Calculate cosine similarity
similarity = cosine_similarity(vectors)

In [162]:
print(vectors.shape)
print(similarity.shape)

(4803, 5000)
(4803, 4803)

In [163]:
# We'll compare it with:

In [164]:
recommend("Avatar")

Movies similar to Avatar:

Jupiter Ascending  → similarity: 0.992
The Martian  → similarity: 0.992
The Amazing Spider-Man  → similarity: 0.991
Spectre  → similarity: 0.991
2012  → similarity: 0.991

In [165]:
recommend("Avatar")

Movies similar to Avatar:

Jupiter Ascending  → similarity: 0.992
The Martian  → similarity: 0.992
The Amazing Spider-Man  → similarity: 0.991
Spectre  → similarity: 0.991
2012  → similarity: 0.991

In [168]:
# saving model 

import os
import pickle

os.makedirs("model", exist_ok=True)

with open("model/similarity.pkl", "wb") as f:
    pickle.dump(similarity, f)

with open("model/movies.pkl", "wb") as f:
    pickle.dump(df, f)

with open("model/vectorizer.pkl", "wb") as f:
    pickle.dump(tfidf, f)

print("All model artifacts saved successfully!")

All model artifacts saved successfully!

In [169]:
#Verify that they were created
import os

print(os.listdir("model"))

['similarity.pkl', 'movies.pkl', 'vectorizer.pkl']

In [170]:
# Reset Dataframe

df = df.reset_index(drop=True)

In [171]:
#Rebuilding 

vectors = tfidf.fit_transform(df["tags"])
similarity = cosine_similarity(vectors)

In [172]:
# Saving again 

import os
import pickle

os.makedirs("model", exist_ok=True)

with open("model/similarity.pkl", "wb") as f:
    pickle.dump(similarity, f)

with open("model/movies.pkl", "wb") as f:
    pickle.dump(df, f)

with open("model/vectorizer.pkl", "wb") as f:
    pickle.dump(tfidf, f)

print("Model artifacts saved successfully!")

Model artifacts saved successfully!

In [173]:
# Creating Api 

from fastapi import FastAPI
import pickle

app = FastAPI(
    title="Movie Recommendation API",
    description="Content-based movie recommendation system",
    version="1.0"
)


# Load model artifacts
with open("model/similarity.pkl", "rb") as f:
    similarity = pickle.load(f)

with open("model/movies.pkl", "rb") as f:
    movies = pickle.load(f)


@app.get("/")
def home():
    return {
        "message": "Movie Recommendation API is running"
    }


@app.get("/recommend/{movie}")
def recommend(movie: str):

    # Find movie
    matches = movies[
        movies["title"].str.lower() == movie.lower()
    ]

    if matches.empty:
        return {
            "error": f"Movie '{movie}' not found"
        }

    # Get movie index
    index = matches.index[0]

    # Get similarity scores
    distances = similarity[index]

    # Sort movies by similarity
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    recommendations = []

    for i, score in movie_list:

        recommendations.append({
            "title": movies.iloc[i]["title"],
            "similarity": round(float(score), 3)
        })

    return {
        "movie": matches.iloc[0]["title"],
        "recommendations": recommendations
    }

In [174]:
{
  "movie": "Avatar",
  "recommendations": [
    {
      "title": "...",
      "similarity": 0.82
    },
    {
      "title": "...",
      "similarity": 0.76
    }
  ]
}

{'movie': 'Avatar',
 'recommendations': [{'title': '...', 'similarity': 0.82},
  {'title': '...', 'similarity': 0.76}]}

In [176]:
#improving API 

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import pickle


# --------------------------------------------------
# 1. Create FastAPI application
# --------------------------------------------------

app = FastAPI(
    title="Movie Recommendation API",
    description="Content-based movie recommendation system",
    version="1.0.0"
)


# --------------------------------------------------
# 2. Load trained artifacts
# --------------------------------------------------

with open("model/similarity.pkl", "rb") as f:
    similarity = pickle.load(f)

with open("model/movies.pkl", "rb") as f:
    movies = pickle.load(f)


# --------------------------------------------------
# 3. Response schema
# --------------------------------------------------

class Recommendation(BaseModel):
    title: str
    similarity: float


class RecommendationResponse(BaseModel):
    movie: str
    recommendations: list[Recommendation]


# --------------------------------------------------
# 4. Health check
# --------------------------------------------------

@app.get("/")
def home():
    return {
        "status": "success",
        "message": "Movie Recommendation API is running"
    }


# --------------------------------------------------
# 5. Recommendation endpoint
# --------------------------------------------------

@app.get(
    "/recommend/{movie}",
    response_model=RecommendationResponse
)
def recommend(movie: str):

    # Find movie
    matches = movies[
        movies["title"].str.lower() == movie.lower()
    ]

    # Movie not found
    if matches.empty:
        raise HTTPException(
            status_code=404,
            detail=f"Movie '{movie}' not found"
        )

    # Get movie index
    index = matches.index[0]

    # Similarity scores
    distances = similarity[index]

    # Sort by similarity
    movie_list = sorted(
        enumerate(distances),
        key=lambda x: x[1],
        reverse=True
    )[1:6]

    recommendations = []

    for i, score in movie_list:

        recommendations.append(
            Recommendation(
                title=movies.iloc[i]["title"],
                similarity=round(float(score), 3)
            )
        )

    return RecommendationResponse(
        movie=matches.iloc[0]["title"],
        recommendations=recommendations
    )